### ISSUE TITLE
Swift 6.2 linker fails to find private symbol SwiftSyntax.SyntaxRewriter.visitationFunc depending on the number of parallel jobs

### ISSUE THREAD

**Issue by ivanovdmitri** [swiftlang/swift-package-manager#9495]
### Description

The error is occurring on macOS and Linux platforms using swift 6.2 release compiler and swift-syntax 602.0.0, and the typical error messages are

on Linux (using the official swift:noble docker image):
```
error: link command failed with exit code 1 (use -v to see invocation)
/thebug/.build/aarch64-unknown-linux-gnu/debug/CasePathsMacros-tool.build/CasePathableMacro.swift.o:CasePathableMacro.swift.o:$s15CasePathsMacros12SelfRewriterCMf:(.data+0x1358): error: undefined reference to '$s11SwiftSyntax0B8RewriterC14visitationFunc33_F0C5D882E9301122F145EADC4573BFC8LL3forAA0B0VAHcAH_tF'
/thebug/.build/aarch64-unknown-linux-gnu/debug/CasePathsMacros-tool.build/CasePathableMacro.swift.o:CasePathableMacro.swift.o:$s15CasePathsMacros15ElementRewriterCMf:(.data+0x2670): error: undefined reference to '$s11SwiftSyntax0B8RewriterC14visitationFunc33_F0C5D882E9301122F145EADC4573BFC8LL3forAA0B0VAHcAH_tF'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[255/327] Linking CasePathsMacros-tool
error: fatalError
```

on macOS 15.7.1, swiftlang-6.2.0.19.9 clang-1700.3.19.1:
```
error: link command failed with exit code 1 (use -v to see invocation)
Undefined symbols for architecture arm64:
  "SwiftSyntax.SyntaxRewriter.(visitationFunc in _F0C5D882E9301122F145EADC4573BFC8)(for: SwiftSyntax.Syntax) -> (SwiftSyntax.Syntax) -> SwiftSyntax.Syntax", referenced from:
      full type metadata for CasePathsMacros.SelfRewriter in CasePathableMacro.swift.o
      full type metadata for CasePathsMacros.ElementRewriter in CasePathableMacro.swift.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[364/373] Linking CasePathsMacros-tool
error: fatalError
```

We have discussed this issue with the maintainers of the https://github.com/pointfreeco/swift-case-paths repository (https://github.com/pointfreeco/swift-case-paths/issues/231) and the conclusion was this issue is occurring in the swift-syntax dependency. 

### Steps to Reproduce

The following appears to reliably reproduce the issue:

1)

```bash
$ mkdir thebug
$ cd thebug
```

add the following `Dockerfile`:

```Dockerfile
FROM swift:noble
WORKDIR /thebug
RUN git clone --branch 1.7.2 --depth 1 https://github.com/pointfreeco/swift-case-paths .
CMD ["swift", "test", "--jobs", "2"]
```

2) run:

```bash
$ docker build -t thebug . && docker run --rm thebug
```

3) get:

```
error: link command failed with exit code 1 (use -v to see invocation)
/thebug/.build/aarch64-unknown-linux-gnu/debug/CasePathsMacros-tool.build/CasePathableMacro.swift.o:CasePathableMacro.swift.o:$s15CasePathsMacros12SelfRewriterCMf:(.data+0x1358): error: undefined reference to '$s11SwiftSyntax0B8RewriterC14visitationFunc33_F0C5D882E9301122F145EADC4573BFC8LL3forAA0B0VAHcAH_tF'
/thebug/.build/aarch64-unknown-linux-gnu/debug/CasePathsMacros-tool.build/CasePathableMacro.swift.o:CasePathableMacro.swift.o:$s15CasePathsMacros15ElementRewriterCMf:(.data+0x2670): error: undefined reference to '$s11SwiftSyntax0B8RewriterC14visitationFunc33_F0C5D882E9301122F145EADC4573BFC8LL3forAA0B0VAHcAH_tF'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[253/327] Linking CasePathsMacros-tool
error: fatalError
```

**Comment by bnbarham** [comment]
`SyntaxRewriter` is part of the `SwiftSyntax` library which basically everything depends on, so seems unlikely to me that there's anything like a missing dependency here. Going to start this over in SwiftPM.

**Comment by ivanovdmitri** [comment]
In this example, restricting the resources to just 2 parallel jobs seems to reliable reproduce this issue.  In the cases of larger dependency trees, this issue shows up sporadically even when we use 4 or 6 cores (e.g. medium / large GitLab SaaS Linux runners) .  The only workaround that reliable works, that I know of, is putting the `swift-syntax` package into "editing mode" via

```bash
$ rm -rf Packages/swift-syntax
$ swift package edit swift-syntax
$ swift build --product CasePathsMacros
```

which re-builds `swift-syntax` from source, instead of using its pre-built libraries.  @bnbarham that is why I originally thought that this is a problem in `swift-syntax`

**Comment by stephencelis** [comment]
It's probably not a great solution, but I've had to convert some `private` funcs to be internal to work around similar symbol resolution issues on Linux. Maybe releasing a version of `swift-syntax` where `visitationFunc` isn't private would help here?

**Comment by stephencelis** [comment]
Swift 6.1 on CI is our workaround, for now: https://github.com/pointfreeco/swift-structured-queries/pull/263

**Comment by dschaefer2** [comment]
I think I have a fix in 6.3, however swift-case-paths doesn't build with the latest 6.3 snapshots.

**Comment by stephencelis** [comment]
@dschaefer2 What snapshot should I try? Is it an compiler assertion failure or something else?

**Comment by dschaefer2** [comment]
I was testing on my Mac with the Jan 29'th 6.3 snapshot. I am getting errors like.

```
.../swift-case-paths/Tests/CasePathsTests/DeprecatedTests.swift:1244:35: error: cannot convert value of type 'Void?' to expected argument type 'Int'
1242 |       for index in 1...maxIterations {
1243 |         group.addTask {
1244 |           XCTAssertEqual(casePath.extract(from: Enum.payload(index)), index)
     |                                   `- error: cannot convert value of type 'Void?' to expected argument type 'Int'
1245 |         }
1246 |       }
```

**Comment by stephencelis** [comment]
@dschaefer2 I can't get that far in the build due to the `Undefined symbols` error above. Those are from deprecated test files, though, which you should be able to comment out. You could also try the `optional-paths` branch which has removed many deprecated APIs.
