### PR TITLE
Rename remaining occurrences of the old helper.

### PR DESCRIPTION
**Pull request by yyvch**
Rename remaining occurrences of the old helper.

### Motivation:

My local test failed to build after #8569 with

```
…/Tests/WorkspaceTests/WorkspaceTests.swift:16148:13: error: cannot find 'skipOnWindowsAsTestCurrentlyFails' in scope
16146 | 
16147 |     func testInvalidTrait_WhenParentPackageEnablesTraits() async throws {
16148 |         try skipOnWindowsAsTestCurrentlyFails(because: #"\tmp\ws doesn't exist in file system"#)
      |             `- error: cannot find 'skipOnWindowsAsTestCurrentlyFails' in scope
16149 | 
16150 |         let sandbox = AbsolutePath("/tmp/ws/")
```

I checked, and it appears to be leftovers after  #8569:

```
% rg skipOnWindowsAsTestCurrentlyFails
Tests/WorkspaceTests/WorkspaceTests.swift
16148:        try skipOnWindowsAsTestCurrentlyFails(because: #"\tmp\ws doesn't exist in file system"#)
16211:        try skipOnWindowsAsTestCurrentlyFails(because: #"\tmp\ws doesn't exist in file system"#)
```

### Modifications:

Renamed `skipOnWindowsAsTestCurrentlyFails` to `XCTSkipOnWindows`.

### Result:

Tests build and pass.

### CODE REVIEW

**Comment by yyvch** [comment]
@swift-ci please test

**Review by bkhouri — APPROVED** [review]

**Comment by bkhouri** [comment]
I wonder how this was missed!  Sorry for impacting you!

**Comment by yyvch** [comment]
> I wonder how this was missed!

Two in-flight PRs modifying the same file, pass individually but fail when merged:

 - #8370 introducing the two new calls for skipOnWindowsAsTestCurrentlyFails
 - #8569 renaming skipOnWindowsAsTestCurrentlyFails to XCTSkipOnWindows

**Comment by bnbarham** [comment]
Merging to unblock PR testing
