### ISSUE TITLE
Testing macros in the OSS toolchain snapshots for macOS don't seem to work with SDK bundles

### ISSUE THREAD

**Issue by finagolfin** [swiftlang/swift-package-manager#8362]
### Description

I recently added the Testing library to my Android SDK bundles for Swift 6.1 and 6.2, finagolfin/swift-android-sdk@eb1567b1c, and it works well to cross-compile Testing tests using the latest linux snapshot toolchain and [my CI-generated 6.1 SDK bundle](https://github.com/finagolfin/swift-android-sdk/actions/runs/13757332853), which I checked by cross-compiling @tayloraswift's swift-png and its tests. 😄

However, @marcprux tells me the same didn't work with the OSS mac toolchain snapshot when he tried it with another Testing repo, as he got errors saying:
```
error: external macro implementation type 'TestingMacros.TestDeclarationMacro' could not be found for macro 'Test'; plugin for module 'TestingMacros' not found
```
suggesting there is some issue with how these Testing macros are installed on macOS.

### Reproduction

Follow [the instructions to use my Android SDK bundle on macOS](https://github.com/finagolfin/swift-android-sdk?tab=readme-ov-file#cross-compiling-and-testing-swift-packages-with-the-android-sdk-bundle), except using the 6.1 bundle linked above, not 6.0.3 as I have not backported the Android patches in this repo to that tag. An alternative would be to try [the linux SDK bundle generated by swift-sdk-generator](https://github.com/swiftlang/swift-sdk-generator), if it supports this Testing library.

### Expected behavior

Testing tests cross-compile fine using the mac toolchain's prebuilt macros, as they do on linux.

### Environment

MacOS

### Additional information

I have not reproduced this myself. Marc said he'd file this himself, but I'm doing it now so we don't forget and so somebody behind this repo can take a look in the meantime.

**Comment by finagolfin** [comment]
Thanks for likely finding the culprit, but my read of the code is that it is still broken in trunk for cross-compilation to non-mac platforms, because [it checks the target triple instead of the host triple before applying the macOS plugin paths](https://github.com/swiftlang/swift-package-manager/blob/8493d0b90382f627bdb9f3e25cb5ff6af7d45f3a/Sources/PackageModel/UserToolchain.swift#L637):
```
        self.targetTriple = triple

        var swiftCompilerFlags: [String] = []
        var extraLinkerFlags: [String] = []

        let swiftTestingPath: AbsolutePath? = try Self.deriveSwiftTestingPath(
            derivedSwiftCompiler: swiftCompilers.compile,
            swiftSDK: self.swiftSDK,
            triple: triple,
            environment: environment,
            fileSystem: fileSystem
        )

        if triple.isMacOSX, let swiftTestingPath {
            // swift-testing in CommandLineTools, needs extra frameworks search path
            if swiftTestingPath.extension == "framework" {
                swiftCompilerFlags += ["-F", swiftTestingPath.pathString]
            }

            // Otherwise we must have a custom toolchain, add overrides to find its swift-testing ahead of any in the
            // SDK. We expect the library to be in `lib/swift/macosx/testing` and the plugin in
            // `lib/swift/host/plugins/testing`
            if let pluginsPath = try? AbsolutePath(
                validating: "../../host/plugins/testing",
                relativeTo: swiftTestingPath
            ) {
                swiftCompilerFlags += [
                    "-I", swiftTestingPath.pathString,
                    "-L", swiftTestingPath.pathString,
                    "-plugin-path", pluginsPath.pathString,
                ]
            }
        }
```
I think this was broken in #7920 last fall by @xedin, ironically when he was trying to fix cross-compilation to wasm. The issue appears to be that `deriveSwiftTestingPath` is used to determine both host and target paths, so it will need to be split up to determine where these host plugins are separately from the target compilation flags, ie checking both host and target triples separately.

**Comment by marcprux** [comment]
Just to add some data, I have a bare-bones repository https://github.com/marcprux/swift-testing-cross-compile-demo with CI that uses the same Android SDK on both macOS and Ubuntu. You can see the test build output for both hosts at: https://github.com/marcprux/swift-testing-cross-compile-demo/actions/runs/13816030659. Ubuntu passes, but macOS fails:

```
Building for debugging...
[0/13] Write sources
[2/13] Write swift-version--451CF4548FE66429.txt
[4/15] Compiling TestingCrossCompile TestingCrossCompile.swift
[5/15] Emitting module TestingCrossCompile
[6/16] Wrapping AST for TestingCrossCompile for debugging
error: emit-module command failed with exit code 1 (use -v to see invocation)
[8/18] Emitting module TestingCrossCompileTests
/Users/runner/work/swift-testing-cross-compile-demo/swift-testing-cross-compile-demo/Tests/TestingCrossCompileTests/TestingCrossCompileTests.swift:4:12: error: external macro implementation type 'TestingMacros.TestDeclarationMacro' could not be found for macro 'Test'; plugin for module 'TestingMacros' not found
2 | @testable import TestingCrossCompile
3 | 
4 | @Test func example() async throws {
  |            `- error: external macro implementation type 'TestingMacros.TestDeclarationMacro' could not be found for macro 'Test'; plugin for module 'TestingMacros' not found
5 |     // Write your test here and use APIs like `#expect(...)` to check expected conditions.
6 | }

Testing.Test:1:30: note: 'Test' declared here
1 | @attached(peer) public macro Test(_ traits: any TestTrait...) = #externalMacro(module: "TestingMacros", type: "TestDeclarationMacro")
  |                              `- note: 'Test' declared here
[9/18] Compiling TestingCrossCompileTests TestingCrossCompileTests.swift
/Users/runner/work/swift-testing-cross-compile-demo/swift-testing-cross-compile-demo/Tests/TestingCrossCompileTests/TestingCrossCompileTests.swift:4:12: error: external macro implementation type 'TestingMacros.TestDeclarationMacro' could not be found for macro 'Test'; plugin for module 'TestingMacros' not found
2 | @testable import TestingCrossCompile
3 | 
4 | @Test func example() async throws {
  |            `- error: external macro implementation type 'TestingMacros.TestDeclarationMacro' could not be found for macro 'Test'; plugin for module 'TestingMacros' not found
5 |     // Write your test here and use APIs like `#expect(...)` to check expected conditions.
6 | }

Testing.Test:1:30: note: 'Test' declared here
1 | @attached(peer) public macro Test(_ traits: any TestTrait...) = #externalMacro(module: "TestingMacros", type: "TestDeclarationMacro")
  |                              `- note: 'Test' declared here

```

The locally-installed testing libraries on macOS are:

```
zap Toolchains/swift-6.1-DEVELOPMENT-SNAPSHOT-2025-03-07-a.xctoolchain % find . -name '*Test*dylib'
./usr/lib/swift/host/plugins/testing/libTestingMacros.dylib
./usr/lib/swift/macosx/testing/libTesting.dylib
```

And on Ubuntu are:

```
marcprux@skipbox:~/.swiftpm/toolchains/swift-6.1-DEVELOPMENT-SNAPSHOT-2025-03-07-a-ubuntu24.04$ find . -name '*Test*.so'
./usr/lib/swift/linux/libTesting.so
./usr/lib/swift/linux/libXCTest.so
./usr/lib/swift/host/plugins/libTestingMacros.so
```

Let me know if there is any jiggery-pokery I can do with file paths or toolchain config to experiment with getting it working.

**Comment by finagolfin** [comment]
My take is that it is incorrectly not passing in the `-plugin-path` when cross-compiling from macOS to other platforms. So first build it natively for macOS with `-v`, find the `-plugin-path` flag that ends with `/testing`, then pass it in to the cross-compile manually with `-Xswiftc -plugin-path -Xswiftc <found-path>/testing`. That should get it to find the Testing macros at least when cross-compiling, though it may still fail later if missing other flags too.

**Comment by marcprux** [comment]
> Just as a temporary experiment, you could try moving or copying `./usr/lib/swift/host/plugins/testing/libTestingMacros.dylib` to `./usr/lib/swift/host/plugins` (up one level from the `testing/` directory) to confirm my theory that it's a search path issue.

That worked!

```
zap Toolchains/swift-6.1-DEVELOPMENT-SNAPSHOT-2025-03-07-a.xctoolchain % cp usr/lib/swift/host/plugins/testing/libTestingMacros.dylib usr/lib/swift/host/plugins/

zap marcprux/swift-testing-cross-compile-demo % ~/Library/Developer/Toolchains/swift-6.1-DEVELOPMENT-SNAPSHOT-2025-03-07-a.xctoolchain/usr/bin/swift build --swift-sdk x86_64-unknown-linux-android24 --build-tests
Building for debugging...
[20/20] Linking TestingCrossCompilePackageTests.xctest
Build complete! (4.70s)

zap marcprux/swift-testing-cross-compile-demo % file ./.build/x86_64-unknown-linux-android24/debug/TestingCrossCompilePackageTests.xctest

./.build/x86_64-unknown-linux-android24/debug/TestingCrossCompilePackageTests.xctest: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, BuildID[sha1]=98e1897f2e50e8ac19473d0a8fd41f2e6349ee30, with debug_info, not stripped
```

I've also [updated](https://github.com/skiptools/swift-android-action/commit/8fedcc53f8f61661b51c9e3e3fdddca9b69deded) `swift-android-action` to apply this workaround, so now the testing demo is working on both macOS and Ubuntu: https://github.com/marcprux/swift-testing-cross-compile-demo/actions/runs/13819400842

I will "un-apply" the workaround once the fix is available in the macOS toolchain.

**Comment by marcprux** [comment]
While the test package is now cross-compiling for Android with the aforementioned workaround, they are not actually getting executed by the `TestingCrossCompilePackageTests.xctest` command in Android. E.g., see https://github.com/marcprux/swift-testing-cross-compile-demo/actions/runs/13820440573, which shows an (intentional) failure when running locally, but passes when running against Android, regardless of whether it was built on macOS or Ubuntu.

This is likely a separate issue, but I'm mentioning it here to point out that fixing this issue won't entirely get testing working. @finagolfin, when you ran the `swift-png` tests, do you have evidence that the tests were actually executed? E.g., if you add in an intentional failure, do they fail as you would expect?

**Comment by stmontgomery** [comment]
I think a better short-term workaround may be manually passing the plugin search path using `-Xswiftc -plugin-path -Xswiftc <found-path>/testing` as @finagolfin suggested, rather than moving content in the toolchain.

**Comment by grynspan** [comment]
@marcprux I'm not that familiar with GitHub CI, but it looks like it's outright not running the .xctest executable a second time (which is how Swift Testing tests run.)

**Comment by grynspan** [comment]
Ah, yes:

> + adb shell 'cd /data/local/tmp/android-xctest &&  ./TestingCrossCompilePackageTests.xctest '

Your script needs to _also_ run `./TestingCrossCompilePackageTests.xctest --testing-library swift-testing` (or however you might spell that in the script.) Note this command is different from what you'd do when running tests on macOS.

**Comment by marcprux** [comment]
> I think a better short-term workaround may be manually passing the plugin search path using `-Xswiftc -plugin-path -Xswiftc <found-path>/testing` as [@finagolfin](https://github.com/finagolfin) suggested, rather than moving content in the toolchain.

That works too. I'll use that instead. Thanks.

**Comment by marcprux** [comment]
> Your script needs to _also_ run `./TestingCrossCompilePackageTests.xctest --testing-library swift-testing` (or however you might spell that in the script.) Note this command is different from what you'd do when running tests on macOS.

Thanks, that works as expected (in that the expected failure is now [occurring](https://github.com/marcprux/swift-testing-cross-compile-demo/actions/runs/13821238862/job/38666839704)).

@grynspan, do I understand correctly that running `./TestingCrossCompilePackageTests.xctest --testing-library swift-testing` will run *only* the Testing tests, and running without the `--testing-library swift-testing` flag will run *only* the non-Tests (i.e., XCTest) tests? 

If so, I now need to figure out when I should run the tests with that argument, since I don't want to invoke the tests a second time when all they contain are XCTest test cases. I'm guessing I'll just run `patchelf --print-needed TestingCrossCompilePackageTests.xctest` and see if the dependencies list contains `libTesting.so`, unless anyone has a cleverer idea…

**Comment by grynspan** [comment]
> @grynspan, do I understand correctly that running ./TestingCrossCompilePackageTests.xctest --testing-library swift-testing will run only the Testing tests, and running without the --testing-library swift-testing flag will run only the non-Testing (i.e., XCTest) tests?

Correct. The tool basically has two separate `main()` functions, one per library, because (at this time) they don't know how to talk to each other and can't coordinate their `main()` function invocations.

> If so, I now need to figure out when I should run the tests with that argument, since I don't want to invoke the tests a second time when all they contain are XCTest test cases. I'm guessing I'll just run patchelf --print-needed TestingCrossCompilePackageTests.xctest and see if the dependencies list contains libTesting.so, unless anyone has a cleverer idea…

If you run the two commands, they won't (shouldn't!) overlap output. :)

**Comment by grynspan** [comment]
Note also that if there are no Swift Testing tests, the library terminates the test process with a specific error code (`EX_UNAVAILABLE`) to indicate this to the caller, and you probably don't want to treat that code as a failure.

This is all, of course, normally handled by SwiftPM. The exact details of how SwiftPM and Swift Testing interoperate will be subject to change over time as we build out more of our infrastructure.

**Comment by marcprux** [comment]
> Note also that if there are no Swift Testing tests, the library terminates the test process with a specific error code (`EX_UNAVAILABLE`) to indicate this to the caller, and you probably don't want to treat that code as a failure.

I'm assuming that this is what I'm seeing when I run a test suite that doesn't use Testing (e.g., Yams), which outputs [this error](https://github.com/skiptools/swift-android-action/actions/runs/13821235026/job/38666825688#step:5:1864):

```
Error: Invalid option "--testing-library"
Usage: YamsPackageTests.xctest [OPTION]
       YamsPackageTests.xctest [TESTCASE]
```

So I think I will want to probe the binary to see if it links to Testing in order to avoid that, since I expect it will be easier than special-casing certain exit codes to count as passing.

**Comment by grynspan** [comment]
>I'm assuming that this is what I'm seeing when I run a test suite that doesn't use Testing (e.g., Yams), which outputs [this error](https://github.com/skiptools/swift-android-action/actions/runs/13821235026/job/38666825688#step:5:1864):
>
>Error: Invalid option "--testing-library"
>Usage: YamsPackageTests.xctest [OPTION]
>       YamsPackageTests.xctest [TESTCASE]

This is a different problem. For historical reasons, test executables on Linux/etc. can specify a custom main function which prevents SwiftPM from emitting its own main function, and Yams is doing that here. I'd love to remove that feature but there are still a lot of packages that rely on it.

You could still run into this problem if the binary does link to Testing.

**Comment by grynspan** [comment]
Spitballing here, perhaps we could teach `swift test` to create a shell script (batch file on Windows?) that does approximately what it normally does. SwiftPM has enough information to know if it needs to invoke the executable a second time.

**Comment by marcprux** [comment]
> You could still run into this problem if the binary does link to Testing.

Yeah, I just ran into that when testing swift-algorithms.

My current solution (https://github.com/skiptools/swift-android-action/commit/9a5ef5806208cee574ad2842b8e4347256e32763) seems to be working, although it ain't pretty: 

```
adb shell 'cd /data/local/tmp/android-xctest &&  ./swift-algorithmsPackageTests.xctest  &&  ./swift-algorithmsPackageTests.xctest  --testing-library swift-testing && [ $0 -eq 0 ] || [ $0 -eq 69 ]'
```

> (By the end of this, you'll have reimplemented a third of SwiftPM. 😬)

Not quite a third, but I'm getting there 🙃

**Comment by finagolfin** [comment]
Possibly fixed by #8670, Marc, try it with the next trunk snapshot toolchain and let us know.

**Comment by finagolfin** [comment]
@marcprux, would be good to close this if fixed now, let us know since you were trying it.

**Comment by marcprux** [comment]
Feel free to close this (I don't have permission).

**Comment by finagolfin** [comment]
Is it working now?

**Comment by marcprux** [comment]
Yes, it works. Previously I had had to manually specify the `-plugin-path` like so:

```
~/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-07-17-a.xctoolchain/usr/bin/swift build --swift-sdk aarch64-unknown-linux-android28 --build-tests --verbose -Xswiftc -plugin-path -Xswiftc ~/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-07-17-a.xctoolchain/usr/lib/swift/host/plugins/testing
```

…but now it also builds without the `-Xswiftc -plugin-path -Xswiftc …` arguments.

The complete command it executes is:

```
/Users/marc/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-07-17-a.xctoolchain/usr/bin/swift-frontend -frontend -emit-module -experimental-skip-non-inlinable-function-bodies-without-types /opt/src/github/swift-android-sdk/swift-android-samples/testing-sample/.build/aarch64-unknown-linux-android28/debug/LibraryDemoPackageTests.derived/runner.swift -target aarch64-unknown-linux-android28 -Xllvm -aarch64-use-tbi -disable-objc-interop -sdk /Users/marc/Library/org.swift.swiftpm/swift-sdks/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-07-17-a-android-0.1.artifactbundle/swift-android/ndk-sysroot -I /opt/src/github/swift-android-sdk/swift-android-samples/testing-sample/.build/aarch64-unknown-linux-android28/debug/Modules -color-diagnostics -Xcc -fcolor-diagnostics -enable-testing -g -debug-info-format=dwarf -dwarf-version=4 -module-cache-path /opt/src/github/swift-android-sdk/swift-android-samples/testing-sample/.build/aarch64-unknown-linux-android28/debug/ModuleCache -Onone -D SWIFT_PACKAGE -D DEBUG -D SWIFT_MODULE_RESOURCE_BUNDLE_UNAVAILABLE -enable-cross-import-overlays -empty-abi-descriptor -plugin-path /Users/marc/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-07-17-a.xctoolchain/usr/lib/swift/host/plugins/testing -resource-dir /Users/marc/Library/org.swift.swiftpm/swift-sdks/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-07-17-a-android-0.1.artifactbundle/swift-android/swift-resources/usr/lib/swift-aarch64 -enable-anonymous-context-mangled-names -file-compilation-dir /opt/src/github/swift-android-sdk/swift-android-samples/testing-sample -Xcc --sysroot -Xcc /Users/marc/Library/org.swift.swiftpm/swift-sdks/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-07-17-a-android-0.1.artifactbundle/swift-android/ndk-sysroot -Xcc -fPIC -Xcc -g -Xcc -fno-omit-frame-pointer -no-auto-bridging-header-chaining -module-name LibraryDemoPackageTests -package-name testing_sample -in-process-plugin-server-path /Users/marc/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-07-17-a.xctoolchain/usr/lib/swift/host/libSwiftInProcPluginServer.dylib -plugin-path /Users/marc/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-07-17-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Users/marc/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-07-17-a.xctoolchain/usr/local/lib/swift/host/plugins -emit-module-doc-path /opt/src/github/swift-android-sdk/swift-android-samples/testing-sample/.build/aarch64-unknown-linux-android28/debug/Modules/LibraryDemoPackageTests.swiftdoc -emit-module-source-info-path /opt/src/github/swift-android-sdk/swift-android-samples/testing-sample/.build/aarch64-unknown-linux-android28/debug/Modules/LibraryDemoPackageTests.swiftsourceinfo -emit-objc-header-path /opt/src/github/swift-android-sdk/swift-android-samples/testing-sample/.build/aarch64-unknown-linux-android28/debug/LibraryDemoPackageTests.build/include/LibraryDemoPackageTests-Swift.h -serialize-diagnostics-path /opt/src/github/swift-android-sdk/swift-android-samples/testing-sample/.build/aarch64-unknown-linux-android28/debug/LibraryDemoPackageTests.build/LibraryDemoPackageTests.emit-module.dia -emit-dependencies-path /opt/src/github/swift-android-sdk/swift-android-samples/testing-sample/.build/aarch64-unknown-linux-android28/debug/LibraryDemoPackageTests.build/LibraryDemoPackageTests.emit-module.d -parse-as-library -o /opt/src/github/swift-android-sdk/swift-android-samples/testing-sample/.build/aarch64-unknown-linux-android28/debug/Modules/LibraryDemoPackageTests.swiftmodule
```

Which includes three `-plugin-path` arguments:

- `…/usr/lib/swift/host/plugins/testing`
- `…/usr/lib/swift/host/plugins`
- `…/usr/local/lib/swift/host/plugins`

(Note that that last path doesn't actually exist, but it doesn't seem to cause any issues)

I'm exercising this in my end-to-end testing CI at https://github.com/swift-android-sdk/swift-android-samples/tree/main/testing-sample, so we should see if it breaks again.

**Comment by finagolfin** [comment]
OK, fixed by #8670 then, thanks for verifying.
